---

- name: Deploy node-exporter
  hosts: debian12-test
  become: true
  vars_files:
    - secrets.yml
  vars:
    node_exporter_version: 1.8.2
    node_exporter_web_listen_address: "0.0.0.0:8443"
    node_exporter_web_telemetry_path: "/metrics"

    node_exporter_system_user: root

    node_exporter_cert_dir: /etc/node_exporter/
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.cert
      key_file: /etc/node_exporter/tls.key
      client_auth_type: RequireAndVerifyClientCert
      client_ca_file: /etc/node_exporter/ca-cert.crt

  pre_tasks:
    - name: Créer le répertoire pour les certificats TLS
      file:
        path: "{{ node_exporter_cert_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copier le certificat TLS pour Node Exporter
      copy:
        content: "{{ node_tls_cert }}"
        dest: "{{ node_exporter_tls_server_config.cert_file }}"
        mode: '0644'
        owner: root
        group: root

    - name: Copier la clé privée TLS pour Node Exporter
      copy:
        content: "{{ node_tls_key }}"
        dest: "{{ node_exporter_tls_server_config.key_file }}"
        mode: '0400'
        owner: root
        group: root

    - name: Copier le certificat CA
      copy:
        content: "{{ ca_cert }}"
        dest: "{{ node_exporter_tls_server_config.client_ca_file }}"
        mode: '0644'
        owner: root
        group: root

  roles:
    - prometheus.prometheus.node_exporter
